### ISSUE TITLE
Upgrade to django-autocomplete-light v3.9

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1019]
It seems there are breaking changes between DAL v3.8-3.9.

Apparently the initialization outside admins (that is, our entire use case) requires a different type of init making use of `{{ form.media }}`.

Furthermore, there is a deprecation issue which has to be looked into:

`Your custom DAL function "autocomplete_redirect" uses a deprecated event listener that will be removed in future versions.`

I'll take a look into how much changes these will require and if the amount of work is not crazy, will squeeze this into v0.11.0. If not, I'll postpone for now.

References:

- https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#using-autocompletes-outside-the-admin
- https://github.com/yourlabs/django-autocomplete-light/issues/936

**Comment by mikkonie** [comment]
The old style init results in the following Javascript error:

```
jquery-3.5.1.min.js:2 jQuery.Deferred exception: $element.select2 is not a function TypeError: $element.select2 is not a function
    at Object.autocomplete_redirect (http://127.0.0.1:8000/static/projectroles/js/autocomplete_redirect.js:76:18)
    at HTMLSelectElement.initialize (http://127.0.0.1:8000/static/autocomplete_light/autocomplete_light.js:153:42)
    at Function.each (https://code.jquery.com/jquery-3.5.1.min.js:2:2976)
    at S.fn.init.each (https://code.jquery.com/jquery-3.5.1.min.js:2:1454)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/static/autocomplete_light/autocomplete_light.js:185:80)
    at e (https://code.jquery.com/jquery-3.5.1.min.js:2:30005)
    at t (https://code.jquery.com/jquery-3.5.1.min.js:2:30307) undefined
```

**Comment by mikkonie** [comment]
Done. Just needed to remove existing hardcoded includes and use ``{{ form.media }}`` instead. Added a note about this into the major changes doc.
