### ISSUE TITLE
Add django.urls.path support to ProjectAccessMixin.get_project()

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/sodar-core#1047]
### Describe the Bug

The Django 2+ `django.urls.path` is useful as it allows to describe routes with a simpler syntax than regexes, e.g., `ajax/frequencypresets/list-create/<uuid:presetset>/`. However, `ProjectAccessMixin.get_project` does not support this yet.

### How to Reproduce

1. Create a route wth `path`.
2. Write a test class derived from `TestProjectAPIPermissionBase`
3. See the issue

```
======================================================================
ERROR: test_list (variants.tests.test_permissions_ajax.TestFrequencyPresetsListCreateAjaxView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/holtgrem_c/Development/varfish-server/variants/tests/test_permissions_ajax.py", line 28, in test_list
    self.assert_response(url, good_users, 200, method="GET")
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/projectroles/tests/test_permissions.py", line 91, in assert_response
    response = self._send_request(url, method, req_kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/projectroles/tests/test_permissions.py", line 45, in _send_request
    return req_method(url, **req_kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/test.py", line 289, in get
    response = super().get(path, data=data, **extra)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/test.py", line 206, in get
    return self.generic('GET', path, **r)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/test.py", line 234, in generic
    return super().generic(
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/test.py", line 286, in request
    return super().request(**kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/test.py", line 238, in request
    request = super().request(**kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/projectroles/views_api.py", line 123, in has_permission
    project = self.get_project(request=request, kwargs=view.kwargs)
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/site-packages/projectroles/views.py", line 208, in get_project
    if re.match(r'[0-9a-f-]+', v):
  File "/home/holtgrem_c/miniconda3/envs/varfish-server/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

### Expected Behavior

The new Django API with `path` should be supported.

### Screenshots

N/A

### System Information

N/A

**Additional Context**

N/A

**Comment by mikkonie** [comment]
This is not a bug, rather a missing feature. Otherwise I agree that this should be supported. Will see about it in the next release.

**Comment by mikkonie** [comment]
In fact this WAS a bug, missing one `str()` conversion :P Fixed, also added some examples and tests + updated docs.
