### ISSUE TITLE
Crash in remote project sync from KeyError

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1258]
Discovered in staging. Dump below in comments, looking into it now.

**Comment by mikkonie** [comment]
Dump:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/app/src/django-sodar-core/projectroles/views_api.py", line 1251, in get
    sync_data = remote_api.get_source_data(target_site)
  File "/usr/src/app/src/django-sodar-core/projectroles/remote_projects.py", line 279, in get_source_data
    sync_data = self._add_parent_categories(
  File "/usr/src/app/src/django-sodar-core/projectroles/remote_projects.py", line 103, in _add_parent_categories
    and sync_data[project_level] == REMOTE_LEVEL_READ_ROLES

Exception Type: KeyError at /project/api/remote/get/zrqym9s2tbdpbe5v7trxyir6v5lchq9v
Exception Value: 'READ_ROLES'
Request information:
USER: AnonymousUser
```

**Comment by mikkonie** [comment]
Fixed. I still need to figure out why this wasn't caught by tests though.
