### ISSUE TITLE
Random UI test crash in CI from icon rendering

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#1383]
I just witnessed a random UI test crash in CI. The crash was related to icon rendering.

The test in question was `projectroles.tests.test_ui.TestProjectCreateView.test_settings_label_icon`, although I suspect the actual test case doesn't have much to do with it.

This is to be monitored. It might be some problem with `django-iconify==0.3`, the latest selenium version.. or just one of those super random Selenium test crashes which happen once and never again.

**Comment by mikkonie** [comment]
Dump of test failure in CI:

```
======================================================================
ERROR: test_settings_label_icon (projectroles.tests.test_ui.TestProjectCreateView.test_settings_label_icon)
Test rendering of app settings icon for project creation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/sodar-core/sodar-core/projectroles/tests/test_ui.py", line 1693, in test_settings_label_icon
    ).find_element(By.TAG_NAME, 'svg')
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 417, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"svg"}
  (Session info: chrome=122.0.6261.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

**Comment by mikkonie** [comment]
I believe this was related to another test timing bug which got fixed. In any case, I haven't witnessed it occurring in a good while. Closing.
