### ISSUE TITLE
All UI tests entering a perpetual error state in login_and_redirect()

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-core#503]
Been encountering an issue where, suddenly and with no changes to testing, almost all UI tests start timing out on a dev machine.

This must, at least in some aspect, be a problem with the specific machine used for development. However, as the timeout seems to happen in the `login_and_redirect()` function, I should try to see if that can be improved somehow.

Below is a dump of one of these timeouts.

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mnieminen/code/sodar_core/projectroles/tests/test_ui.py", line 500, in test_admin_link
    expected_false, url, 'sodar-navbar-link-admin', False
  File "/home/mnieminen/code/sodar_core/projectroles/tests/test_ui.py", line 342, in assert_element_exists
    self.login_and_redirect(user, url, wait_elem, wait_loc)
  File "/home/mnieminen/code/sodar_core/projectroles/tests/test_ui.py", line 225, in login_and_redirect
    (By.ID, 'sodar-navbar-user-dropdown')
  File "/home/mnieminen/.virtualenvs/sodar_core/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Update:** I tried the "deprecated" login and redirect function and it works! It seems something is wrong with how we set cookies, maybe Chrome/Chromedriver has changed something in the behaviour AGAIN.

As a workaround, should make it possible for the user to use the legacy login method instead. This cookie stuff seems VERY flimsy.

**Comment by mikkonie** [comment]
Old issue, should not be relevant anymore. Closing.
